export const listStyle = {
  bg: `w-screen font-quicksand`,
  container: ` font-quicksand max-w-[500px] w-full h-full m-auto rounded-md p-4`,
  heading: `text-3xl flex font-bold text-white py-2`,
  whiteHeading: `text-3xl flex font-bold text-white py-2`,
  form: `flex justify-between`,
  input: `border p-2 w-full text-xl`,
  button: `border p-4 ml-2 bg-pink text-slate-100`,
  buttons: "flex gap-2 scale-120 ",
  plus: `transition ease-in-out delay-70 hover:scale-130 duration-70`,
  gear: "transition ease-in-out delay-70 transform scale-175 duration-300",
  bottom: `flex flex-col items-center gap-2`,
  count: `text-center p-2`,
  deleteListIcon:
    "scale-130 transition ease-in-out delay-70 hover:scale-150 duration-70",
  deleteListButton: "mt-72 p-4 ",
  deleteAllButton: `flex border p-4 bg-pink`,
  info: `mt-5`,
  link: `text-pink bg-dogwood font-bold`,
};
