export const newListStyle = {
  bg: `w-screen font-quicksand`,
  container: `font-quicksand max-w-[500px] w-full h-full m-auto rounded-md p-4 flex flex-col items-center`,
  bigHeader: "text-4xl flex font-bold mb-4 text-black",
  heading: `text-2xl flex font-bold text-black py-2`,
  form: `flex justify-between`,
  input: `border p-2 my-1 w-full text-xl`,
  button: `border p-4 mt-4 bg-pink text-black w-full`,
  icon: `transition ease-in-out delay-70 hover:scale-130 duration-70`,
  bottom: `flex flex-col items-center gap-2`,
  count: `text-center p-2`,
  deleteAllButton: `flex border p-4 bg-pink`,
  info: `mt-5`,
  link: `text-pink font-bold cursor-pointer`,
};
